/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_getpic_GetPicUsingJni */

#ifndef _Included_com_getpic_GetPicUsingJni
#define _Included_com_getpic_GetPicUsingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_getpic_GetPicUsingJni
 * Method:    getPicFromFrameBuffer
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_getpic_GetPicUsingJni_getPicFromFrameBuffer
  (JNIEnv *, jobject, jint, jint, jint);
  
JNIEXPORT jint JNICALL Java_com_getpic_GetPicUsingJni_getRectPicFromFrameBuffer
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
